# these recipies will be removed once the sheduler is working
# they are currently being used for for bootstrapping the scheduler

RABBITMQ_PORT := "5672"
RABBITMQ_HOSTNAME := "dagyorabbitmq"
GREET_JOBS := "greetfakejobid"
SOURCE_JOBS := "sourcefakejobid"

rabbitmq:
    docker run --name {{ RABBITMQ_HOSTNAME }} -p {{ RABBITMQ_PORT }}:5672 --rm rabbitmq

greet:
    #!/bin/bash
    set -ueo pipefail

    dbuild_args="--build-arg SCRIPT=./greet.py --file all.dockerfile ."

    docker build $dbuild_args
    docker run \
        -e DAGYO_JOBS={{ GREET_JOBS }} \
        -e DAGYO_QUEUE="amqp://guest:guest@{{ RABBITMQ_HOSTNAME }}:{{ RABBITMQ_PORT }}/" \
        --link {{ RABBITMQ_HOSTNAME }}:{{ RABBITMQ_HOSTNAME }} \
        --rm $(docker build -q $dbuild_args)

source:
    #!/bin/bash
    set -ueo pipefail

    dbuild_args="--build-arg SCRIPT=./source.py --file all.dockerfile ."

    docker build $dbuild_args
    docker run \
        -e DAGYO_JOBS={{ SOURCE_JOBS }} \
        -e DAGYO_QUEUE="amqp://guest:guest@{{ RABBITMQ_HOSTNAME }}:{{ RABBITMQ_PORT }}/" \
        --link {{ RABBITMQ_HOSTNAME }}:{{ RABBITMQ_HOSTNAME }} \
        --rm $(docker build -q $dbuild_args)

